### PR TITLE
Fix and add shit

### PR DESCRIPTION
**Pull request by Craftzman7**

### CODE REVIEW

**Comment by Ne-k** [comment]
😐

**Comment by Craftzman7** [comment]
review it pls

**Comment by Craftzman7** [comment]
@NekWasTaken review this lol

**Comment by Craftzman7** [comment]
welp conflicts resolved. this can be merged again.

**Comment by Craftzman7** [comment]
nek pls

**Comment by Craftzman7** [comment]
> Tomorrow or sometime later so shut up.

no u

**Comment by Craftzman7** [comment]
dead chat xd

**Comment by Ne-k** [comment]
Fine fine I'm testing it.

**Comment by Ne-k** [comment]
But to be honest, the python isn't useful because I can't run unsharded with my bot over 3k servers.

**Comment by Craftzman7** [comment]
Eh more for dev use

**Pull request merged**
